"""
GitHub Service — creates repos and pushes generated code.
"""
import os
import subprocess
import tempfile
import shutil
from pathlib import Path
from typing import Optional


def get_token() -> str:
    """Read GitHub token from file or env."""
    token_file = Path.home() / ".github_token"
    if token_file.exists():
        return token_file.read_text().strip()
    return os.getenv("GITHUB_TOKEN", "")


def create_repo(project_name: str, description: str = "") -> dict:
    """Create a new GitHub repo via gh CLI."""
    token = get_token()
    if not token:
        raise RuntimeError("No GitHub token found. Set GITHUB_TOKEN or ~/.github_token")

    # Use gh CLI if available
    result = subprocess.run(
        ["gh", "repo", "create", project_name, "--public", "--description", description or f"Generated by FutureReady", "--confirm"],
        capture_output=True,
        text=True,
        env={**os.environ, "GH_TOKEN": token},
    )

    if result.returncode != 0 and "already exists" not in result.stderr:
        raise RuntimeError(f"gh repo create failed: {result.stderr}")

    # Get the repo URL
    user_result = subprocess.run(
        ["gh", "api", "user", "-q", ".login"],
        capture_output=True,
        text=True,
        env={**os.environ, "GH_TOKEN": token},
    )
    username = user_result.stdout.strip() or "getclients4u-lab"

    return {
        "name": project_name,
        "owner": username,
        "url": f"https://github.com/{username}/{project_name}",
        "clone_url": f"https://github.com/{username}/{project_name}.git",
    }


def push_code(workspace: Path, repo: dict) -> dict:
    """Push generated code from workspace to the GitHub repo."""
    token = get_token()
    clone_url = repo["clone_url"].replace("https://", f"https://{token}@")

    # Initialize git in workspace
    subprocess.run(["git", "init"], cwd=workspace, capture_output=True)
    subprocess.run(["git", "checkout", "-b", "main"], cwd=workspace, capture_output=True)
    subprocess.run(["git", "add", "."], cwd=workspace, capture_output=True)
    subprocess.run(
        ["git", "commit", "-m", "Initial commit — generated by FutureReady Orchestrator"],
        cwd=workspace,
        capture_output=True,
    )

    # Add remote and push
    subprocess.run(["git", "remote", "add", "origin", clone_url], cwd=workspace, capture_output=True)
    result = subprocess.run(
        ["git", "push", "-u", "origin", "main", "--force"],
        cwd=workspace,
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        raise RuntimeError(f"git push failed: {result.stderr}")

    return {
        "repo_url": repo["url"],
        "commit_count": 1,
        "files_pushed": len(list(workspace.rglob("*"))),
    }


def repo_exists(project_name: str) -> bool:
    """Check if a repo already exists."""
    token = get_token()
    result = subprocess.run(
        ["gh", "repo", "view", project_name],
        capture_output=True,
        text=True,
        env={**os.environ, "GH_TOKEN": token},
    )
    return result.returncode == 0
